version: "3.8"

services:
  dash-app:
    build:
      context: .
      dockerfile: Dockerfile.light
    ports:
      - "8050:8050"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    volumes:
      # Optional: mount data directory for easier updates
      - ./data:/app/data
